# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z07TCeIT6uIKq7xf6pOpX7BfqU3N-cxo
"""

import streamlit as st
import cv2
import numpy as np
import torch
from PIL import Image

# Load your trained YOLO model (example)
model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt')

def load_image(image_file):
    img = Image.open(image_file)
    return img

def predict_back_length(image):
    # Perform object detection using YOLOv8
    results = model(image)
    # Extract bounding box coordinates
    boxes = results.xyxy[0].numpy()  # assuming the first element is bounding box coordinates
    back_lengths = []
    for box in boxes:
        x1, y1, x2, y2, conf, cls = box
        # Calculate back length as the distance between the points
        back_length = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)
        back_lengths.append(back_length)
    return back_lengths, results

st.title("Elephant Back Length Measurement")
st.write("Upload an image of an elephant to measure its back length.")

image_file = st.file_uploader("Upload Image", type=["png", "jpg", "jpeg"])

if image_file is not None:
    img = load_image(image_file)
    st.image(img, caption='Uploaded Image', use_column_width=True)

    with st.spinner('Processing...'):
        back_lengths, results = predict_back_length(np.array(img))

    st.success('Done!')

    st.write("Detected Back Lengths (in pixels):")
    for length in back_lengths:
        st.write(f"{length:.2f} pixels")

    # Display the image with bounding boxes
    st.image(results.render()[0], caption='Detected Elephants', use_column_width=True)

st.write("Note: The model detects the back length of elephants in the uploaded image.")